In [1]:
import torch
import torch.nn as nn

In [2]:
class NeuralNet(nn.Module):
    def __init__(self):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(1, 8)
        self.fc2 = nn.Linear(8, 4)
        self.output = nn.Linear(4, 1)
    
    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.output(x)
        return x

In [3]:
ann = NeuralNet()

In [28]:
criterion = nn.MSELoss()
optim = torch.optim.Adam(ann.parameters(), lr=0.01)

In [23]:
X_data = torch.Tensor([[-10], [-5], [9], [100]])
y_data = torch.Tensor([[-88], [-43], [83], [902]])

In [49]:
for epoch in range(500):
    optim.zero_grad()
    y_hat = ann(X_data)
    loss = criterion(y_hat, y_data)
    loss.backward()
    optim.step()
    
    print('Epoch : ', epoch, ' -'*10, ' Loss : ', loss.item())

Epoch :  0  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  1  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  2  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  3  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  4  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  5  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  6  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  7  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  8  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  9  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  10  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  11  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  12  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  13  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  14  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  15  - - - - - - - - - -  Loss :  3

Epoch :  136  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  137  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  138  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  139  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  140  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  141  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  142  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  143  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  144  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  145  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  146  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  147  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  148  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  149  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  150  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  151  - - 

Epoch :  374  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  375  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  376  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  377  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  378  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  379  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  380  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  381  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  382  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  383  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  384  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  385  - - - - - - - - - -  Loss :  1.8189894035458565e-11
Epoch :  386  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  387  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  388  - - - - - - - - - -  Loss :  3.637978807091713e-12
Epoch :  389  - -

In [32]:
x = torch.Tensor([-80])
print(ann(x))

tensor([-717.4277], grad_fn=<AddBackward0>)


In [43]:
print('Weight FC 1 \n', ann.fc1.weight, '\n', ann.fc1.weight.size())
print('Weight FC 2 \n', ann.fc2.weight, '\n', ann.fc2.weight.size())
print('Weight Output \n', ann.output.weight, '\n', ann.output.weight.size())

Weight FC 1 
 Parameter containing:
tensor([[-0.6813],
        [-0.8972],
        [-1.1511],
        [-0.7119],
        [ 0.9099],
        [-1.1277],
        [-0.2450],
        [-1.4947]], requires_grad=True) 
 torch.Size([8, 1])
Weight FC 2 
 Parameter containing:
tensor([[-0.6228, -0.8144, -0.7334, -0.5141,  0.5950, -0.2808, -0.4174, -0.5827],
        [ 0.2952,  0.4626,  0.8008,  0.2205, -0.6588,  0.5691,  0.3005,  0.4992],
        [-0.3060, -0.2599, -0.2843, -0.0833,  0.7281, -0.5834, -0.3472, -0.3646],
        [ 0.1960,  0.4086,  0.5343,  0.0811, -0.4766,  0.3841,  0.0700,  0.6476]],
       requires_grad=True) 
 torch.Size([4, 8])
Weight Output 
 Parameter containing:
tensor([[ 0.4918, -0.9174,  0.3938, -0.7913]], requires_grad=True) 
 torch.Size([1, 4])
