In [1]:
import torch

In [4]:
#Uninitialized  Matrix
x = torch.empty(5, 3)
print(x)

tensor([[9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38],
        [4.2246e-39, 1.0378e-38, 9.6429e-39],
        [9.2755e-39, 9.7346e-39, 1.0745e-38]])


In [7]:
#Random Matrix
x = torch.rand(2, 3)
print(x)

tensor([[0.8719, 0.7003, 0.1984],
        [0.5123, 0.5026, 0.4485]])


In [8]:
#Zero Matrix
x = torch.zeros(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [14]:
#Tensor
x = torch.tensor([[5.0, 10.0], [4.0, 1.0], [3.0, 3.0], [2.0, 5.0]])
print(x)
print(x.size())

tensor([[ 5., 10.],
        [ 4.,  1.],
        [ 3.,  3.],
        [ 2.,  5.]])
torch.Size([4, 2])


In [21]:
#Add Tensor
x = torch.rand(4,4)
y = torch.rand(4, 4)
print(x)
print(y)
print(torch.add(x, y))
print(x[2:,])

tensor([[0.1244, 0.6400, 0.7903, 0.3039],
        [0.2860, 0.9197, 0.0906, 0.6367],
        [0.6160, 0.8659, 0.6077, 0.3376],
        [0.1889, 0.2444, 0.0334, 0.9718]])
tensor([[0.1802, 0.9125, 0.9455, 0.2489],
        [0.6934, 0.5299, 0.3536, 0.1101],
        [0.6481, 0.5268, 0.8925, 0.9971],
        [0.5467, 0.9964, 0.4896, 0.8401]])
tensor([[0.3046, 1.5525, 1.7358, 0.5528],
        [0.9794, 1.4497, 0.4442, 0.7468],
        [1.2640, 1.3927, 1.5001, 1.3347],
        [0.7356, 1.2408, 0.5230, 1.8118]])
tensor([[0.6160, 0.8659, 0.6077, 0.3376],
        [0.1889, 0.2444, 0.0334, 0.9718]])


In [29]:
#Resize
x = torch.rand(3,3)
y = x.view(9)
z = x.view(-1, 9)
print(x)
print(y)
print(z)
print(x.size(), y.size(), z.size())

tensor([[0.2639, 0.7376, 0.5197],
        [0.4868, 0.8638, 0.1291],
        [0.0627, 0.8420, 0.5188]])
tensor([0.2639, 0.7376, 0.5197, 0.4868, 0.8638, 0.1291, 0.0627, 0.8420, 0.5188])
tensor([[0.2639, 0.7376, 0.5197, 0.4868, 0.8638, 0.1291, 0.0627, 0.8420, 0.5188]])
torch.Size([3, 3]) torch.Size([9]) torch.Size([1, 9])


In [35]:
#Autograd 
x = torch.rand(2, 2, requires_grad=True)
y = x + 3
print(y)
print(y.grad_fn)
z = y**2
out = z.mean()
print(z)
print(out)

tensor([[3.7962, 3.5785],
        [3.6418, 3.1764]], grad_fn=<AddBackward0>)
tensor([[14.4115, 12.8060],
        [13.2629, 10.0896]], grad_fn=<PowBackward0>)
tensor(12.6425, grad_fn=<MeanBackward0>)


In [36]:
out.backward()
print(x.grad)

tensor([[1.8981, 1.7893],
        [1.8209, 1.5882]])


In [43]:
from torch.autograd import Variable


In [69]:
ze = torch.tensor([2.0], requires_grad=True)
out = ze**3
print(ze)
print(out)
out.backward(ze)
print(ze.grad)

tensor([2.], requires_grad=True)
tensor([8.], grad_fn=<PowBackward0>)
tensor([24.])
